# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  database: my_porsche
  user: root
  password: 

production:
  host: mysql.mekdigital.com
  adapter: mysql
  database: my_porsche
  user: etozzato
  password: g-401a